# Generated by Django 3.1.3 on 2021-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Name this Equipment', max_length=255)),
                ('total_qty', models.IntegerField()),
                ('location', models.CharField(default='Physics Office', max_length=20)),
                ('img_reference', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
