# Generated by Django 3.1.3 on 2021-01-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_equipment',
            old_name='total_qty',
            new_name='total_quantity',
        ),
    ]
