# Generated by Django 3.1.3 on 2021-01-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210119_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='img_reference',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='location',
            field=models.CharField(choices=[('Room 1', 'Room 1'), ('Room 2', 'Room 2'), ('Room 3', 'Room 3'), ('Room 4', 'Room 4'), ('Room 5', 'Room 5')], default='Physics Office', max_length=20),
        ),
    ]
