# Generated by Django 3.1.3 on 2021-01-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210125_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
