# Generated by Django 3.1.3 on 2021-02-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210127_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_equipment',
            name='quantity_new',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
