# Generated by Django 3.1.3 on 2021-02-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210204_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_equipment',
            name='quantity_new',
        ),
    ]
