# Generated by Django 3.1.3 on 2021-02-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210206_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='name',
            field=models.CharField(blank=True, default='Name this Equipment', max_length=255, null=True),
        ),
    ]
