# Generated by Django 3.1.3 on 2021-02-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210206_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='location',
            field=models.CharField(blank=True, default='Physics Office', max_length=20),
        ),
    ]
