# Generated by Django 3.1.3 on 2021-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210207_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='img_reference',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded/'),
        ),
    ]
