# Generated by Django 3.1.3 on 2021-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210207_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='location',
            field=models.CharField(default='Physics Office', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='name',
            field=models.CharField(default='Name this Equipment', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
