# Generated by Django 3.1.3 on 2021-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210211_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='location',
            field=models.CharField(blank=True, default='Physics Office', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='name',
            field=models.CharField(blank=True, default='Name this Equipment', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
