# Generated by Django 3.1.3 on 2021-02-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210211_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='name',
            field=models.CharField(blank=True, default='Name this Equipment', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory_equipment',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
