# Generated by Django 3.1.3 on 2021-02-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210211_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
