# Generated by Django 3.1.3 on 2021-02-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210215_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'practical',
            },
        ),
        migrations.CreateModel(
            name='Practical_Equipment_Needed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_quantity', models.IntegerField(default=0)),
                ('equipment_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory_equipment')),
                ('practical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.practical')),
            ],
            options={
                'db_table': 'practical_equipment_needed',
            },
        ),
        migrations.AddField(
            model_name='practical',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, through='inventory.Practical_Equipment_Needed', to='inventory.Inventory_Equipment'),
        ),
    ]
