# Generated by Django 3.1.3 on 2021-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210216_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_equipment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
