# Generated by Django 3.1.3 on 2021-02-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20210216_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practical',
            name='practical_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
