# Generated by Django 3.1.3 on 2021-03-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210226_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.CharField(choices=[('Lesson 1', 'Lesson 1'), ('Lesson 2', 'Lesson 2'), ('Lesson 3', 'Lesson 3'), ('Lesson 4', 'Lesson 4'), ('Lesson 5', 'Lesson 5')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('period_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.period')),
                ('practical_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.practical')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.staff')),
            ],
            options={
                'db_table': 'Lesson_Bookings',
            },
        ),
    ]
