# Generated by Django 3.1.3 on 2021-03-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210305_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='staff',
            field=models.ForeignKey(default='Name the Staff', on_delete=django.db.models.deletion.CASCADE, to='inventory.staff'),
        ),
    ]
