# Generated by Django 3.1.3 on 2021-03-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20210305_2222'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='period',
            table='period_number',
        ),
    ]
